// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqOcWT7PAZnG8wzMwdLGs2uvthTrZpMQ4',
    appId: '1:558285605963:web:004fb72cb48002279251ce',
    messagingSenderId: '558285605963',
    projectId: 'parkwizauth-cfa38',
    authDomain: 'parkwizauth-cfa38.firebaseapp.com',
    storageBucket: 'parkwizauth-cfa38.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-_FzBMgx5mP6HZKb9hHjtqbSpNkDPja0',
    appId: '1:558285605963:android:6fb00508fdd683759251ce',
    messagingSenderId: '558285605963',
    projectId: 'parkwizauth-cfa38',
    storageBucket: 'parkwizauth-cfa38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLL6kw00Q8Em-8_flnRaIXvHtKiusUX8A',
    appId: '1:558285605963:ios:7f384b37e8da5ff99251ce',
    messagingSenderId: '558285605963',
    projectId: 'parkwizauth-cfa38',
    storageBucket: 'parkwizauth-cfa38.appspot.com',
    iosBundleId: 'com.example.parkwizflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLL6kw00Q8Em-8_flnRaIXvHtKiusUX8A',
    appId: '1:558285605963:ios:3ae6af77dba5a9229251ce',
    messagingSenderId: '558285605963',
    projectId: 'parkwizauth-cfa38',
    storageBucket: 'parkwizauth-cfa38.appspot.com',
    iosBundleId: 'com.example.parkwizflutter.RunnerTests',
  );
}
